name: 'Attempt build'
description: 'Attempts to build lots of different languages.'
runs:
  using: "composite"
  steps:
    - name: Set versions
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
          echo "RUBY_VERSION=$(cat .ruby-version)" >> $GITHUB_ENV
    
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: ${{ env.RUBY_VERSION }}
    
    - uses: actions/setup-node@v2
      with:
          node-version: ${{ env.NODE_VERSION }}
    
    - run: ${{ github.action_path }}/run_builds.sh
      shell: bash